name: Build and Deploy to VM

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
            ls
            cd ci-cd-next-app
            npm run build
            pm2 start npm run start
